fix(example): fixes styled-components example
[L21](https://github.com/zeit/next.js/blob/98cf0a83116270150fabee595264dd7a848f3304/examples/with-styled-components/pages/_document.js#L21) attempts to use `Object.seal()` by calling `.seal()` as a method on `sheet` imported module. 

this usage breaks the app with `TypeError: sheet.seal is not a function` so I went ahead and fixed it up ☺.